DROP TABLE Parts CASCADE CONSTRAINTS
DROP TABLE Orders CASCADE CONSTRAINTS
DROP TABLE PartOrder CASCADE CONSTRAINTS
DROP TABLE Employee CASCADE CONSTRAINTS
DROP TABLE Telephone CASCADE CONSTRAINTS
DROP TABLE Customer CASCADE CONSTRAINTS